In [1]:
import numpy as np
import scipy as sp
import sympy as sym
import matplotlib.pyplot as plt
import pandas as pd
import re

# Example 1

## Equations

In [2]:
a = np.array([
    [3, 9, -3],
    [1, -3, 11],
    [-2, 5, -20]
])

b = np.array([
    [24],
    [-2],
    [-5]
])

In [3]:
c = np.c_[a, b]

In [4]:
c

array([[  3,   9,  -3,  24],
       [  1,  -3,  11,  -2],
       [ -2,   5, -20,  -5]])

In [5]:
np.sort(c, axis=0)

array([[ -2,  -3, -20,  -5],
       [  1,   5,  -3,  -2],
       [  3,   9,  11,  24]])

In [6]:
# number of dimensions
np.ndim(c)

2

In [7]:
# total number of elements
np.size(c)

12

In [8]:
# shape of array
np.shape(c)

(3, 4)

In [9]:
c

array([[  3,   9,  -3,  24],
       [  1,  -3,  11,  -2],
       [ -2,   5, -20,  -5]])

In [10]:
d = c.astype('float').copy()

## Put the system in reduced row echelon form

In [11]:
d

array([[  3.,   9.,  -3.,  24.],
       [  1.,  -3.,  11.,  -2.],
       [ -2.,   5., -20.,  -5.]])

### Find the pivot entry in the first row.

In [12]:
# step 1
d[0][:] = ((1 / 3) * d[0])

In [13]:
d

array([[  1.,   3.,  -1.,   8.],
       [  1.,  -3.,  11.,  -2.],
       [ -2.,   5., -20.,  -5.]])

### Zero out the rest of the first column

In [14]:
# step 2
d[1][:] = (-1 * d[0][:]) + d[1][:]

In [15]:
d

array([[  1.,   3.,  -1.,   8.],
       [  0.,  -6.,  12., -10.],
       [ -2.,   5., -20.,  -5.]])

In [16]:
# step 3
d[2][:] = (2 * d[0][:]) + d[2][:]

In [17]:
d

array([[  1.,   3.,  -1.,   8.],
       [  0.,  -6.,  12., -10.],
       [  0.,  11., -22.,  11.]])

### Find the pivot entry in the second row

In [18]:
# step 4
d[1][:] = (-1 / 6) * d[1][:]

In [19]:
d

array([[  1.        ,   3.        ,  -1.        ,   8.        ],
       [ -0.        ,   1.        ,  -2.        ,   1.66666667],
       [  0.        ,  11.        , -22.        ,  11.        ]])

### Zero out the rest of the second column

In [20]:
# step 5
d[0][:] = (-3 * d[1][:]) + d[0][:]

In [21]:
d

array([[  1.        ,   0.        ,   5.        ,   3.        ],
       [ -0.        ,   1.        ,  -2.        ,   1.66666667],
       [  0.        ,  11.        , -22.        ,  11.        ]])

In [22]:
# step 6
d[2][:] = (-11 * d[1][:]) + d[2][:]

In [23]:
d

array([[ 1.        ,  0.        ,  5.        ,  3.        ],
       [-0.        ,  1.        , -2.        ,  1.66666667],
       [ 0.        ,  0.        ,  0.        , -7.33333333]])

# Example 2

## Equations

Question: Determine whether the system has one solution, no solutions, or
infinitely many solutions.

w + 2x − 3y + 7z = 4

3w − x − 2y = 12

−2w + 5x + 2z = 5

2w + 3x − 5y + 11z = 8

In [24]:
a = [
    [1, 2, -3, 7],
    [3, -1, -2, 0],
    [-2, 5, 0, 2],
    [2, 3, -5, 11]
]

b = [
    [4],
    [12],
    [5],
    [8]
]

In [25]:
c = np.c_[a, b]
d = c.astype('float').copy()

## Put the system in reduced row echelon form

### Column [0]

In [26]:
d

array([[ 1.,  2., -3.,  7.,  4.],
       [ 3., -1., -2.,  0., 12.],
       [-2.,  5.,  0.,  2.,  5.],
       [ 2.,  3., -5., 11.,  8.]])

In [27]:
# step 1
d[2][:] = d[2][:] + d[3][:]
d

array([[ 1.,  2., -3.,  7.,  4.],
       [ 3., -1., -2.,  0., 12.],
       [ 0.,  8., -5., 13., 13.],
       [ 2.,  3., -5., 11.,  8.]])

In [28]:
# step 2
d[1][:] = d[1][:] - d[0][:]
d

array([[ 1.,  2., -3.,  7.,  4.],
       [ 2., -3.,  1., -7.,  8.],
       [ 0.,  8., -5., 13., 13.],
       [ 2.,  3., -5., 11.,  8.]])

In [29]:
# step 3
d[[1, 2], :] = d[[2, 1], :]
d

array([[ 1.,  2., -3.,  7.,  4.],
       [ 0.,  8., -5., 13., 13.],
       [ 2., -3.,  1., -7.,  8.],
       [ 2.,  3., -5., 11.,  8.]])

In [30]:
# step 4
d[2][:] = d[2][:] - d[3][:]
d

array([[  1.,   2.,  -3.,   7.,   4.],
       [  0.,   8.,  -5.,  13.,  13.],
       [  0.,  -6.,   6., -18.,   0.],
       [  2.,   3.,  -5.,  11.,   8.]])

In [31]:
# step 5
d[3][:] = (2 * d[0][:]) - d[3][:]
d

array([[  1.,   2.,  -3.,   7.,   4.],
       [  0.,   8.,  -5.,  13.,  13.],
       [  0.,  -6.,   6., -18.,   0.],
       [  0.,   1.,  -1.,   3.,   0.]])

In [32]:
d

array([[  1.,   2.,  -3.,   7.,   4.],
       [  0.,   8.,  -5.,  13.,  13.],
       [  0.,  -6.,   6., -18.,   0.],
       [  0.,   1.,  -1.,   3.,   0.]])

### Column [1]

In [33]:
# step 6
d[[1, 3], :] = d[[3, 1], :]

In [34]:
d

array([[  1.,   2.,  -3.,   7.,   4.],
       [  0.,   1.,  -1.,   3.,   0.],
       [  0.,  -6.,   6., -18.,   0.],
       [  0.,   8.,  -5.,  13.,  13.]])

In [35]:
# step 7
d[0][:] = d[0][:] - (2 * d[1][:])

In [36]:
d

array([[  1.,   0.,  -1.,   1.,   4.],
       [  0.,   1.,  -1.,   3.,   0.],
       [  0.,  -6.,   6., -18.,   0.],
       [  0.,   8.,  -5.,  13.,  13.]])

In [37]:
# step 8
d[3][:] = d[3][:] + d[2][:]

In [38]:
d

array([[  1.,   0.,  -1.,   1.,   4.],
       [  0.,   1.,  -1.,   3.,   0.],
       [  0.,  -6.,   6., -18.,   0.],
       [  0.,   2.,   1.,  -5.,  13.]])

In [39]:
# step 9
d[2][:] = d[2][:] + (3 * d[3][:])
d

array([[  1.,   0.,  -1.,   1.,   4.],
       [  0.,   1.,  -1.,   3.,   0.],
       [  0.,   0.,   9., -33.,  39.],
       [  0.,   2.,   1.,  -5.,  13.]])

In [40]:
# step 10
d[3][:] = d[3][:] - (2 * d[1][:])
d

array([[  1.,   0.,  -1.,   1.,   4.],
       [  0.,   1.,  -1.,   3.,   0.],
       [  0.,   0.,   9., -33.,  39.],
       [  0.,   0.,   3., -11.,  13.]])

### Column [2]

In [41]:
# step 11
d[3][:] = d[2][:] - (3 * d[3][:])

In [42]:
d

array([[  1.,   0.,  -1.,   1.,   4.],
       [  0.,   1.,  -1.,   3.,   0.],
       [  0.,   0.,   9., -33.,  39.],
       [  0.,   0.,   0.,   0.,   0.]])

In [43]:
d[2][:] / 9

array([ 0.        ,  0.        ,  1.        , -3.66666667,  4.33333333])