In [2]:
import re
import numpy as np
import scipy as sp
import sympy as sym
from IPython.display import display, Math, Latex
import math
import matplotlib.pyplot as plt

# Multiplying Matrices by Vectors
***

In [3]:
a = np.array([[1, 0], [-2, 4], [0, 1]])
print(a.shape)
print(a)

(3, 2)
[[ 1  0]
 [-2  4]
 [ 0  1]]


In [4]:
b = np.array([[5], [-1]])
print(b.shape)
print(b)

(2, 1)
[[ 5]
 [-1]]


In [5]:
a @ b

array([[  5],
       [-14],
       [ -1]])

In [6]:
ab = np.array([
    [(a[0][0] * b[0][0]) + (a[0][1] * b[1][0])],
    [(a[1][0] * b[0][0]) + (a[1][1] * b[1][0])],
    [(a[2][0] * b[0][0]) + (a[2][1] * b[1][0])]
])

In [7]:
ab

array([[  5],
       [-14],
       [ -1]])

In [8]:
(a[0][1] * b[1])

array([0])

# Null Space and Ax=0
***
Null space is a subspace of a vector space.
1. Includes the zero vector.
2. Closed under addition
3. Closed under scalar multiplication


In [9]:
display(Math(
    r'\overrightarrow{X} \space that \space satisfies \space A\overrightarrow{X} = \overrightarrow{0} \space is \space in \space the \space null \space space \space N(A)'))

<IPython.core.display.Math object>

In [10]:
A = np.array([
    [1, -4, 3],
    [2, 4, 2],
    [-1, -5, 0]
])

x = np.array([-5, 1, 3])

In [11]:
O = A * x

In [12]:
O.sum()

0

In [13]:
A = np.array([
    [-3, 1, 9],
    [1, 1, 1]
])

In [14]:
(A * np.array([2, -3, 1])).sum()

0

In [15]:
A = np.array([
    [5, 3, 1, 5],
    [-10, -2, 1, -3],
    [-5, 1, 2, 4],
    [7, 1, -1, -2]
])

In [16]:
(A * np.array([-1, 3, -4, 0])).sum()

0

# Null Space of a Matrix
***

In [17]:
A = np.array([
    [2, 0, -1, 2],
    [-4, 0, 2, -4],
    [-6, 0, -3, -6],

], dtype=np.float64)

In [18]:
# Put in RREF

In [19]:
# step 1
A_1 = A.copy()
A_1[0][:] = A_1[0][:] / 2
A_1

array([[ 1. ,  0. , -0.5,  1. ],
       [-4. ,  0. ,  2. , -4. ],
       [-6. ,  0. , -3. , -6. ]])

In [20]:
# step 2
A_2 = A_1.copy()
A_2[1][:] = A_2[1][:] * (1 / 4)
A_2[1][:] = A_2[1][:] + A_1[0][:]
A_2

array([[ 1. ,  0. , -0.5,  1. ],
       [ 0. ,  0. ,  0. ,  0. ],
       [-6. ,  0. , -3. , -6. ]])

In [21]:
# step 3
A_3 = A_2.copy()
A_3[2][:] = A_3[2][:] * (1 / 6)
A_3[2][:] = A_3[2][:] + A_2[0][:]
A_3

array([[ 1. ,  0. , -0.5,  1. ],
       [ 0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. , -1. ,  0. ]])

In [22]:
# step 4
A_4 = A_3.copy()
A_4[2][:] = A_4[2][:] * (1 / 2)
A_4[0][:] = A_4[0][:] - A_4[2][:]
A_4[2][:] = abs(A_4[2][:] * -2)
A_4

array([[1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [23]:
# step 5
A_5 = A_4.copy()
A_5[[2, 1], :] = A_5[[1, 2], :]
A_5

array([[1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]])

In [24]:
# Question 1
# Find the null space of A

A = np.array([
    [1, -1, -2],
    [0, -1, 4],
    [6, -6, -12],
])

In [25]:
A_1 = A.copy()
A_1[2][:] = A_1[2][:] / 6

A_1[0][:] = A_1[0][:] - A_1[1][:]
A_1[1][:] = A_1[1][:] * -1
A_1[2][:] = A_1[2][:] - A_1[0][:]
A_1[2][:] = A_1[1][:] + A_1[2][:]
# A_1[0][:] = A_1[0][:] - A_1[1][:]
# A_1[1][:] = A_1[1][:] * (1/2)
A_1

array([[ 1,  0, -6],
       [ 0,  1, -4],
       [ 0,  0,  0]])

# Column Space and Ax=b

In [26]:
display(Math(r'The \space column \space space \space and \space A\overrightarrow{x} = \overrightarrow{b}'))

<IPython.core.display.Math object>

In [27]:
display(Math(r'N(A) is the \space NULL \space space \space of \space A = A\overrightarrow{x} = \overrightarrow{0}'))
display(Math(
    r'C(A) \space is \space the \space COLUMN \space space \space of \space of A = linear \space combination \space of \space the \space columns \space of \space A'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [28]:
A = np.array([
    [2, 4],
    [3, 6]
])

In [29]:
print(f'C(A) = span({A[:][0]}, {A[:][1]})')

C(A) = span([2 4], [3 6])


In [30]:
display(Math(
    r'if \space \overrightarrow{b} \space \in \space C(A), \space then \space \overrightarrow{x} \space exists \space as \space a \space solution'))

<IPython.core.display.Math object>

In [31]:
display(Math(
    r'if \space N(A) \space = \space \overrightarrow{0}, \space then \space columns \space of \space A \space are \space linearly \space independent'))
display(Math(
    r'if \space N(A) \space = \space \overrightarrow{0}, \space \overrightarrow{v} \space then \space columns \space of \space A \space are \space linearly \space dependent'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [32]:
# Example 1

A = np.array([
    [2, 4],
    [3, 6]
])

vec_b = np.array([6, 9])

In [33]:
# step 1 RREF

A_1 = A.copy()
A_1[0][:] = A_1[0][:] / 2
A_1[1][:] = A_1[1][:] / 3
A_1[1][:] = A_1[1][:] - A_1[0][:]
A_1

array([[1, 2],
       [0, 0]])

In [34]:
x_1 = display(Math(r'{x_1}'))
x_2 = display(Math(r'{x_2}'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

# Dimensionality, Nullity, Rank
***

In [35]:
A = np.array([
    [2, 0, 4, -2],
    [1, 3, -1, 0],
    [0, -2, 1, 1]
], dtype='float64')
A

array([[ 2.,  0.,  4., -2.],
       [ 1.,  3., -1.,  0.],
       [ 0., -2.,  1.,  1.]])

In [36]:
def format_matrix(A):
    rows = [
        " & ".join(str(int(val)) if val == int(val) else str(val) for val in row)
        for row in A
    ]
    body = r"\\ ".join(rows)
    return r"\begin{bmatrix}" + body + r"\end{bmatrix}"


In [37]:
display(Math(format_matrix(A)))

<IPython.core.display.Math object>

In [38]:
# Step 1: RREF

A_1 = A.copy()
A_1[0][:] = A_1[0][:] / 2
A_1[[2, 1], :] = A_1[[1, 2], :]
A_1[[0, 2], :] = A_1[[2, 0], :]
A_1[2][:] = A_1[2][:] - A_1[0][:]
A_1[2][:] = (-1 * (A_1[2][:]))
A_1[2][:] = A_1[1][:] + A_1[2][:]
A_1[[2, 1], :] = A_1[[1, 2], :]
A_1[0][:] = A_1[0][:] + A_1[2][:]
A_1[2][:] = (-1 / 2) * A_1[2][:]
A_1[[2, 1], :] = A_1[[1, 2], :]
A_1[0][:] = A_1[0][:] - A_1[1][:]
A_1[2][:] = A_1[2][:] - A_1[1][:]
A_1[2][:] = (-1 / 2) * A_1[2][:]
A_1

array([[ 1.  ,  0.  ,  0.5 ,  1.5 ],
       [-0.  ,  1.  , -0.5 , -0.5 ],
       [-0.  , -0.  ,  0.75, -1.25]])

In [39]:
 # Question 1

M = np.array([
    [1, -2, 3, -2, 3],
    [-3, 6, -9, 3, -6],
    [-5, 9, -7, 3, 0]
], dtype='float64')

O = np.array([0, 0, 0], dtype='float64')

M

array([[ 1., -2.,  3., -2.,  3.],
       [-3.,  6., -9.,  3., -6.],
       [-5.,  9., -7.,  3.,  0.]])

In [40]:
A = np.c_[M, O]
A

array([[ 1., -2.,  3., -2.,  3.,  0.],
       [-3.,  6., -9.,  3., -6.,  0.],
       [-5.,  9., -7.,  3.,  0.,  0.]])

In [41]:
A_1 = A.copy()
A_1[1][:] = A_1[1][:] * (-1 / 3)
A_1[2][:] = A_1[2][:] * (-1 / 5)
A_1[1][:] = A_1[1][:] - A_1[2][:]
A_1[2][:] = A_1[2][:] - A_1[0][:]
A_1[2][:] = A_1[1][:] + A_1[2][:]
A_1[0][:] = A_1[1][:] + A_1[0][:]
A_1[1][:] = A_1[1][:] * -1
A_1[0][:] = A_1[0][:] + (3 * A_1[1][:])
# A_1[2][:] = A_1[2][:] * -1

A_1

array([[ 1. , -1.6, -0.2, -1.2, -1. ,  0. ],
       [-0. ,  0.2, -1.6,  0.4, -2. , -0. ],
       [ 0. ,  0. ,  0. ,  1. , -1. ,  0. ]])

In [42]:
A = np.array([
    [1, 3, -2, -1, 0],
    [2, 5, -4, -7, 3],
    [1, 4, -3, 5, 4],
    [1, 2, -2, -6, 3]
])

In [43]:
A_1 = A.copy()
A_1[2][:] = A_1[2][:] * 2
A_1[3][:] = A_1[3][:] * 2
A_1[1][:] = A_1[1][:] - A_1[2][:]
A_1[2][:] = A_1[2][:] - A_1[3][:]
A_1[3][:] = A_1[2][:] - (2 * A_1[2][:])
A_1[1][:] = A_1[1][:] + A_1[2][:]
A_1[2][:] = A_1[2][:] + A_1[3][:]
A_1[3][:] = (4 * A_1[1][:]) + A_1[3][:]
A_1[[3, 2], :] = A_1[[2, 3], :]
A_1[2][:] = (A_1[2][:] * (1 / 2))
A_1[0][:] = A_1[0][:] - (3 * A_1[1][:])
A_1[0][:] = A_1[0][:] + (2 * A_1[2][:])
A_1

array([[  1,   0,   0, -18,  -5],
       [  0,   1,   0,   5,  -3],
       [  0,   0,   1,  -1,  -7],
       [  0,   0,   0,   0,   0]])