In [1]:
import numpy as np
import scipy as sp
import sympy as sym
import matplotlib.pyplot as plt
import pandas as pd
import re

# Matrix Addition and Subtraction

In [2]:
a = np.array([
    [8, 2],
    [7, 9]
])

b = np.array([
    [2, 3],
    [3, 1]
])

c = np.array([
    [5, 7],
    [-5, 9]
])

d = np.array([
    [2, 0],
    [6, -4]
])

In [3]:
x = a - b

In [4]:
x

array([[ 6, -1],
       [ 4,  8]])

In [5]:
x - (c + d)

array([[-1, -8],
       [ 3,  3]])

# Scalar Multiplication

In [6]:
a = np.array([
    [5, 2, 1],
    [-2, 4, 7]
])

In [7]:
4 * a

array([[20,  8,  4],
       [-8, 16, 28]])

In [8]:
a = np.array([
    [7, 1],
    [8, 3]
])

b = np.array([
    [0, -5],
    [-2, 3]
])

In [9]:
x = -4 * b

In [10]:
x - 3 * a

array([[-21,  17],
       [-16, -21]])

In [11]:
a = np.array([
    [4, -2, 0],
    [-8, 10, -5]
])

b = np.array([
    [-1, 0, -3],
    [5, -5, 0]
])

In [12]:
(-1 / 2) * a + (3 * b)

array([[ -5. ,   1. ,  -9. ],
       [ 19. , -20. ,   2.5]])

# Zero Matrices

In [13]:
O_2x2 = np.zeros([2, 2])

In [14]:
O_2x2

array([[0., 0.],
       [0., 0.]])

In [15]:
b

array([[-1,  0, -3],
       [ 5, -5,  0]])

In [16]:
# opposite matrix of b
-1 * b

array([[ 1,  0,  3],
       [-5,  5,  0]])

In [17]:
b + (-1 * b)

array([[0, 0, 0],
       [0, 0, 0]])

# Matrix Multiplication

In [18]:
a

array([[ 4, -2,  0],
       [-8, 10, -5]])

In [19]:
b

array([[-1,  0, -3],
       [ 5, -5,  0]])

In [20]:
a * b

array([[ -4,   0,   0],
       [-40, -50,   0]])

In [21]:
c = np.array([
    [2, 3],
    [-1, 0]
])

d = np.array([
    [0, 1],
    [0, -1]
])

In [22]:
print(c)
print(d)

[[ 2  3]
 [-1  0]]
[[ 0  1]
 [ 0 -1]]


In [23]:
x_0_0 = (c[0][0] * d[0][0]) + (c[0][1] * d[1][0])

In [24]:
x_0_1 = (c[0][0] * d[0][1]) + (c[0][1] * d[1][1])

In [25]:
x_1_0 = (c[1][0] * d[0][0]) + (c[1][1] * d[1][0])

In [26]:
x_1_1 = (c[1][0] * d[0][1]) + (c[1][1] * d[1][1])

In [27]:
x = np.array([
    [x_0_0, x_0_1],
    [x_1_0, x_1_1]
])

In [28]:
x

array([[ 0, -1],
       [ 0, -1]])

In [29]:
c.dot(d)

array([[ 0, -1],
       [ 0, -1]])

In [30]:
# 4R x 2C * 2R x 6C = 4R x 6C

# matrix multiplication is not commutative
# A * B != B * A

# matrix multiplication is associative 
# (A * B) * C = A * (B * C)

# matrix multiplication is distributive
# A * (B + C) = A * B + A * C
# but 
# (A + B) * C = A * C + B * C


In [31]:
# 3 x 2
a = np.array([
    [2, 0],
    [1, 0],
    [1, 4]
])

# 2 x 2
b = np.array([
    [1, 0],
    [-1, 3]
])

In [32]:
# 3 x 2
a.dot(b)

array([[ 2,  0],
       [ 1,  0],
       [-3, 12]])

In [33]:
a = np.array([
    [5, 2],
    [0, -2]
])

b = np.array([
    [9, 1],
    [6, -1]
])

In [34]:
x_0_0 = (a[0][0] * b[0][0]) + (a[0][1] * b[1][0])
x_0_1 = (a[0][0] * b[0][1]) + (a[0][1] * b[1][1])

x_1_0 = (a[1][0] * b[0][0]) + (a[1][1] * b[1][0])
x_1_1 = (a[1][0] * b[0][1]) + (a[1][1] * b[1][1])

In [35]:
x = np.array([
    [x_0_0, x_0_1],
    [x_1_0, x_1_1]
])

In [36]:
x

array([[ 57,   3],
       [-12,   2]])

In [37]:
a.dot(b)

array([[ 57,   3],
       [-12,   2]])

In [38]:
a = np.array([
    [7, 2, -4],
    [-5, 10, 3]
])

b = np.array([
    [7, 1],
    [7, 2],
    [-2, 6]
])

In [39]:
a.dot(b)

array([[ 71, -13],
       [ 29,  33]])

In [40]:
a = np.array([
    [3, -1],
    [1, 4]
])

b = np.array([
    [5, 2],
    [-2, 3]
])

c = np.array([
    [2, 0],
    [6, 2]
])

In [41]:
a.dot(b) + a.dot(c)

array([[17,  1],
       [23, 22]])

# Identity Matrix
A matrix that can be multiplied by the original matrix to give the original matrix.

An identity matrix is a square matrix with 1s on the diagonal and 0s everywhere else.

In [42]:
I = np.identity(3, dtype=int)

In [43]:
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [44]:
I = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

In [45]:
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
from fractions import Fraction

In [47]:
Fraction(.25)

Fraction(1, 4)

In [48]:
a = np.array([
    [3, 55, 2],
    [1, 2, 3],
    [4, 5, 6]
])

In [49]:
a.dot(I)

array([[ 3, 55,  2],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [50]:
# the identity matrix shape comes from the row size of the original matrix in a square formation (ie. 3 x 5 matrix would be 3 x 3 identity matrix)

# Elimination Matrix
AI = A

IA = A


A(-1)A = I

AA(-1) = I

EA = I =>  Elimination Matrix


In [51]:
a = np.array([
    [2, 4],
    [0, -3]
])

In [52]:
a.astype(int)

array([[ 2,  4],
       [ 0, -3]])

In [53]:
b = a.copy()

In [54]:
a

array([[ 2,  4],
       [ 0, -3]])

In [55]:
b[0][:] * .5

array([1., 2.])

In [56]:
b[0][:] = b[0][:] * .5

In [57]:
b

array([[ 1,  2],
       [ 0, -3]])

In [58]:
(b[1][:] * -1) - b[0][:]

array([-1,  1])

In [59]:
(-1 * b[0][:]) + (b[1][:])

array([-1, -5])

In [60]:
b[1][:] = b[1][:] * (-1 / 3)

In [61]:
b

array([[1, 2],
       [0, 1]])

In [62]:
b[0][:] = b[0][:] - (2 * b[1][:])

In [63]:
b

array([[1, 0],
       [0, 1]])