In [1]:
import re
import numpy as np
import scipy as sp
import sympy as sym
from IPython.display import display, Math, Latex
import math
import matplotlib.pyplot as plt
from fractions import Fraction

# Transposes and their Determinants
***

In [2]:
a = np.array([
    [1, 1, -2],
    [2, 3, 1],
    [3, -3, 4]
])

b = np.array([
    [4, -6, 1],
    [0, -8, 5],
    [1, 1, -2]
])

In [3]:
# Question 1: Question: Find (AB)T

(a * b).transpose()

array([[  4,   0,   3],
       [ -6, -24,  -3],
       [ -2,   5,  -8]])

In [4]:
a.transpose().dot(b.transpose())

array([[ -5,  -1,  -3],
       [-17, -39,  10],
       [-10,  12,  -9]])

In [5]:
a.transpose() * b.transpose()

array([[  4,   0,   3],
       [ -6, -24,  -3],
       [ -2,   5,  -8]])

In [6]:
b.transpose()

array([[ 4,  0,  1],
       [-6, -8,  1],
       [ 1,  5, -2]])

In [7]:
# Question 2: Find the sum of two transposed matrices

(a + b).transpose()

array([[ 5,  2,  4],
       [-5, -5, -2],
       [-1,  6,  2]])

In [8]:
# Question 3: : Find (A−1)T. 

In [9]:
np.linalg.inv(a).transpose()

array([[ 0.375, -0.125, -0.375],
       [ 0.05 ,  0.25 ,  0.15 ],
       [ 0.175, -0.125,  0.025]])

In [10]:
A = sym.Matrix(a.copy())

In [11]:
M = A.inv().transpose()

In [12]:
M

Matrix([
[ 3/8, -1/8, -3/8],
[1/20,  1/4, 3/20],
[7/40, -1/8, 1/40]])

# Null and Column Spaces of the Transposed Matrix
***

In [13]:
a = np.array([
    [1, -3],
    [0, 1],
    [4, 0]
])



In [14]:
M = sym.Matrix(a.copy())

In [15]:
M_t = M.transpose()

Z = sym.zeros(2, 1)

In [16]:
M_t

Matrix([
[ 1, 0, 4],
[-3, 1, 0]])

In [17]:
Z

Matrix([
[0],
[0]])

In [18]:
result = M_t.row_join(Z)

result

Matrix([
[ 1, 0, 4, 0],
[-3, 1, 0, 0]])

In [19]:
R = result.rref()[0]

In [20]:
R

Matrix([
[1, 0,  4, 0],
[0, 1, 12, 0]])

In [21]:
# Find the null space and the nullity of A

In [22]:
A = sym.Matrix(np.array([
    [1, -2, 2, 3, -1],
    [-3, 6, -1, 1, -7],
    [2, -4, 5, 8, -4]
]))

In [23]:
A

Matrix([
[ 1, -2,  2, 3, -1],
[-3,  6, -1, 1, -7],
[ 2, -4,  5, 8, -4]])

In [24]:
# Find RREF of A
rref = A.rref()[0]
rref

Matrix([
[1, -2, 0, -1,  3],
[0,  0, 1,  2, -2],
[0,  0, 0,  0,  0]])

In [25]:
# Create an Augmented Matrix A
A_aug = rref.row_join(sym.zeros(3, 1))
A_aug

Matrix([
[1, -2, 0, -1,  3, 0],
[0,  0, 1,  2, -2, 0],
[0,  0, 0,  0,  0, 0]])

In [26]:
# each column of the augmented matrix represents a pivot column (ie. x_1, x_2, x_3)

# In the matrix A_aug, column 1, and 3 are the pivot columns and the remaining columns are free variables

# We want to solve Ax = 0 for the leading variables

# EQ1: x_1 - 2x_2 + 0x_3 + -1x_4 + 3x_5 = 0
# EQ2: x_3 + 2x_4 - -2x_5 = 0

In [27]:
# EQ1: x_1 = 2x_2 + x_4 - 3x_5
# EQ2: x_3 = 2x_4 - 2x_5

In [28]:

#          [[ x_1 ],           [[  (0x_1)    +    2x_2     +     0x_3    +      1x_4     +  -3x_5    ],   () => pivot column
#          [ x_2 ],             [   0x_1     +   (1x_2)    +     0x_3    +      0x_4     +   0x_5    ],   () => pivot column
#   x =    [ x_3 ],      =      [   0x_1     +    0x_2     +     0x_3    +     -2x_4     +   2x_5    ],
#          [ x_4 ],             [   0x_1     +    0x_2     +     0x_3    +      1x_4     +   0x_5    ],
#          [ x_5 ]]             [   0x_1     +    0x_2     +     0x_3    +      0_x4     +   0x_5    ]]   

In [29]:

#         [[ x_1 ],            [[  2x_2   ]      [  1x_4  ]          [  -3x_5   ],   () => pivot column
#          [ x_2 ],             [ (1x_2)  ]      [  0x_4  ]          [   0x_5   ],   () => pivot column
#   x =    [ x_3 ],      =      [  0x_2   ]  +   [ -2x_4  ]   +      [   2x_5   ],
#          [ x_4 ],             [  0x_2   ]      [  1x_4  ]          [   0x_5   ],
#          [ x_5 ]]             [  0x_2   ]      [  0_x4  ]          [   0x_5   ]]   


In [30]:

#         [[ x_1 ],                [[ 2 ]           [ 1 ]              [ -3 ],  
#          [ x_2 ],                 [ 1 ]           [ 0 ]              [ 0 ],  
#   x =    [ x_3 ],      =   x_2    [ 0 ]  +  x_4   [ -2 ]   +   x_5   [ 2 ],
#          [ x_4 ],                 [ 0 ]           [ 1 ]              [ 0 ],
#          [ x_5 ]]                 [ 0 ]           [ 0 ]              [ 0 ]]   


In [31]:
#                      [[ 2 ]       [ 1 ]         [ -3 ],  
#                       [ 1 ]       [ 0 ]         [ 0 ],  
#   null(A) = span of   [ 0 ]  +    [ -2 ]   +    [ 2 ],
#                       [ 0 ]       [ 1 ]         [ 0 ],
#                       [ 0 ]       [ 0 ]         [ 0 ]]  

In [32]:
# Nullity(A) = 3

# Product of Matrix and its Transpose
***

In [33]:
a = np.array([
    [2, 1],
    [0, -3],
    [1, 0]
])

In [34]:
A = sym.Matrix(a.copy())
print(A.shape)
A

(3, 2)


Matrix([
[2,  1],
[0, -3],
[1,  0]])

In [35]:
At = A.transpose()
at = a.transpose()
print(At.shape)
At

(2, 3)


Matrix([
[2,  0, 1],
[1, -3, 0]])

In [36]:
at.dot(a)

array([[ 5,  2],
       [ 2, 10]])

In [37]:
# Topic: The product of a matrix and its transpose
# Question: Is AT A invertible?

a = np.array([
    [-6, 3],
    [4, -2]
])

at = np.transpose(a)

R = sym.Matrix(at.dot(a)).rref()[0]

# If R is the identity matrix, then AT(A) is invertible.
R

Matrix([
[1, -1/2],
[0,    0]])

In [38]:
# Topic: The product of a matrix and its transpose
# Question: Is AT A invertible?

a = np.array([
    [1, 0, 1],
    [0, -2, 1],
    [-2, 3, -2]
])

at = np.transpose(a)

R = sym.Matrix(at.dot(a)).rref()[0]

# If R is the identity matrix, then AT(A) is invertible.
R

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

# A=LU Factorization
***

In [39]:
a = np.array([
    [2, 1],
    [8, 1]
], dtype='float')
a

array([[2., 1.],
       [8., 1.]])

In [40]:
e2_1 = np.array([
    [1, 0],
    [(-16 / 2), 1]
], dtype='float')

In [41]:
a_1 = a.dot(e2_1)
a_1

array([[-6.,  1.],
       [ 0.,  1.]])

In [42]:
np.linalg.inv(a_1)

array([[-0.16666667,  0.16666667],
       [ 0.        ,  1.        ]])

In [43]:
# Question: Rewrite A as L(U)

a = np.array([
    [3, 6],
    [-6, 10]
], dtype='float')

e2_1 = np.array([
    [1, 0],
    [2, 1]
])

u = np.linalg.inv(e2_1)
u

array([[ 1.,  0.],
       [-2.,  1.]])