In [1]:
import re
import numpy as np
import scipy as sp
import sympy as sym
from IPython.display import display, Math, Latex
import math
import matplotlib.pyplot as plt
from fractions import Fraction

# Functions and Transformations
***
domain => what we are mapping from

codomain => what we are mapping to

range => specific points in the codomain that were mapped to by the function

In [2]:
display(Math(r'T: \space \mathbb{R}^3 \rightarrow \mathbb{R}^3'))

<IPython.core.display.Math object>

vector valued function is also known as a Transformation

not all vectors may be transformed and so the range does not always cover the entire codomain


In [3]:
display(Math(r'T: \space \mathbb{R}^3 \rightarrow \mathbb{R}^2'))
display(Math(r'T: \space A: \space domain \to B: \space codomain \to \space range'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

# Transformation Matrices and the Image of the Subset

In [4]:
# Question 1

a = np.array([-4, 2])

Q = np.array([[11, 1], [0, -6]])

In [5]:
b = np.dot(Q, a)
b

array([-42, -12])

In [6]:
# Question 2

a = np.array([
    [-2, 1],
    [1, 3],
    [2, -2],
    [-3, -1]
])

P = np.array([
    [-2, 0]
    , [1, 3]
])

In [7]:
for row in a:
    print(np.dot(P, row))

[4 1]
[-2 10]
[-4 -4]
[ 6 -6]


# Image, Preimage, and Kernel
***

In [8]:
def find_preimage(T, B_1):
    T_x_B1_0 = np.c_[T_x, B_1[0]]

    T_x_B1_1 = np.c_[T_x, B_1[1]]

    T_x_B1_0_rref = np.array(sym.Matrix(T_x_B1_0).rref()[0])

    T_x_B1_1_rref = np.array(sym.Matrix(T_x_B1_1).rref()[0])

    x_01 = (np.c_[
        T_x_B1_0_rref[0][-1],
        T_x_B1_0_rref[1][-1]
    ]).transpose()

    x_02 = (np.c_[

        T_x_B1_1_rref[0][-1],
        T_x_B1_1_rref[1][-1]
    ]).transpose()

    # Display the augmented matrices
    print('Augmented Matrix -> T_x_B1_0:')
    display(Math(sym.latex(sym.Matrix(T_x_B1_0))))

    print('Augmented Matrix -> T_x_B1_0_rref:')
    display(Math(sym.latex(sym.Matrix(T_x_B1_0_rref))))

    print('\n' + '-' * 80 + '\n')

    # Display the RREF of the augmented matrices
    print('RREF of the augmented matrices -> T_x_B1_1:')
    display(Math(sym.latex(sym.Matrix(T_x_B1_1))))

    print('RREF of the augmented matrices -> T_x_B1_1_rref:')
    display(Math(sym.latex(sym.Matrix(T_x_B1_1_rref))))

    print('\n' + '-' * 80 + '\n')

    # Display the preimage to image mapping
    print('Pre-Image A1:')
    A1 = np.c_[x_01, x_02]
    display(Math(sym.latex(sym.Matrix(A1))))

    print('Image B1:')
    B1 = np.c_[B_1[0], B_1[1]]
    display(Math(sym.latex(sym.Matrix(B1))))

    print('\n' + '-' * 80 + '\n')


In [9]:
# Question 1
# Find the preimage A1 of the subset B1 under the transformation 
B_1 = ([1, -2], [3, 5])

T_x = np.array([[1, -1], [0, 3]])

In [10]:
T_x

array([[ 1, -1],
       [ 0,  3]])

In [11]:
find_preimage(T_x, B_1)

Augmented Matrix -> T_x_B1_0:


<IPython.core.display.Math object>

Augmented Matrix -> T_x_B1_0_rref:


<IPython.core.display.Math object>


--------------------------------------------------------------------------------

RREF of the augmented matrices -> T_x_B1_1:


<IPython.core.display.Math object>

RREF of the augmented matrices -> T_x_B1_1_rref:


<IPython.core.display.Math object>


--------------------------------------------------------------------------------

Pre-Image A1:


<IPython.core.display.Math object>

Image B1:


<IPython.core.display.Math object>


--------------------------------------------------------------------------------



In [12]:
# Question 2

In [13]:
B_1 = ([-3, 0], [2, 2])

T_x = np.array([[-2, 0], [1, 4]])

In [14]:
T_x

array([[-2,  0],
       [ 1,  4]])

In [15]:
find_preimage(T_x, B_1)

Augmented Matrix -> T_x_B1_0:


<IPython.core.display.Math object>

Augmented Matrix -> T_x_B1_0_rref:


<IPython.core.display.Math object>


--------------------------------------------------------------------------------

RREF of the augmented matrices -> T_x_B1_1:


<IPython.core.display.Math object>

RREF of the augmented matrices -> T_x_B1_1_rref:


<IPython.core.display.Math object>


--------------------------------------------------------------------------------

Pre-Image A1:


<IPython.core.display.Math object>

Image B1:


<IPython.core.display.Math object>


--------------------------------------------------------------------------------



In [16]:
print('Preimage A1 x2:')
preimage_A1["x_02"]

Preimage A1 x2:


NameError: name 'preimage_A1' is not defined

In [ ]:
B_1 = ([5, -2], [-3, 1])

T_x = np.array([[1, -2], [1, 4]])

In [ ]:
find_preimage(T_x, B_1)

# Linear Transformation as Matrix-Vector Product
***

In [ ]:
display(Math(r'T: \space \mathbb{R}^n \rightarrow \mathbb{R}^m'))

In [ ]:
# the transformation of their sum is equivalent to the sum of their individual transformations
display(Math(r'T(\overrightarrow{u} + \overrightarrow{v}) = T(\overrightarrow{u})) + T(\overrightarrow{v})'))

In [ ]:
# and the transformation of a scalar multiple of the vector is equivalent to the product of the scalar and the transformation of the original vector
display(Math(
    r'T(c \overrightarrow{u}) = c T(\overrightarrow{u}) \space and \space T(c \overrightarrow{u}) = c T(\overrightarrow{u})'))


In [ ]:
# Question: Use a matrix-vector product to reflect the square with vertices(−3,2), (4,2), (4, − 5), and (−3, − 5) over the x-axis. What are the vertices of the reflected square?

In [ ]:
R_x = np.array([[1, 0], [0, -1]])  # -1 multiplication on the y-axis
vertices = np.array([[-3, 2], [4, 2], [4, -5], [-3, -5]])
reflected_vertices = np.dot(vertices, R_x)
reflected_vertices

In [ ]:
R_x = np.array([[2, 0], [0, 1]])  # 2 multiplication on identity matrix
vertices = np.array([[-3, 6], [3, 1], [-1, 1], [-1, -6]])
vertices

In [ ]:
np.dot(vertices, R_x)

R_x = np.array([[-1, 0], [0, (1/3)]])  # reflect over y-axis then compress it vertically by factor of 3
vertices = np.array([[1,1], [0,4], [-4,-4], [-3, 1]])
np.dot(vertices, R_x)

# Linear Transformations as Rotations
***

In [ ]:
print('\n' + '-' * 80 + '\n')

display(Math(r'''\mathbb{R}^2\theta \space = \space \left[\begin{matrix}
\cos{\left(\theta \right)} & -\sin{\left(\theta \right)} \\
\sin{\left(\theta \right)} & \cos{\left(\theta \right)}
\end{matrix}\right]'''))

print('\n' + '-' * 80 + '\n')


In [ ]:
display(Math(r'\mathbb{R}^3\theta \space = '))

print('\n' + '-' * 80 + '\n')

display(Math(r'''Rot_{\theta\text{ around x}} \space = \begin{bmatrix}
1 & 0 & 0 \\\
0 & \cos{\left(\theta \right)} & -\sin{\left(\theta \right)} \\
0 & \sin{\left(\theta \right)} & \cos{\left(\theta \right)}
\end{bmatrix}'''))

print('\n' + '-' * 80 + '\n')

display(Math(r'''Rot_{\theta\text{ around y}} \space = \begin{bmatrix}
\cos{\left(\theta \right)} & 0 & \sin{\left(\theta \right)} \\\
0 & 1 & 0 \\
-\sin{\left(\theta \right)} & 0 & \cos{\left(\theta \right)}
\end{bmatrix}'''))

print('\n' + '-' * 80 + '\n')

display(Math(r'''Rot_{\theta\text{ around z}} \space = \begin{bmatrix}
\cos{\left(\theta \right)} & -\sin{\left(\theta \right)} & 0 \\\
\sin{\left(\theta \right)} & \cos{\left(\theta \right)} & 0 \\
0 & 0 & 1 \\
\end{bmatrix}'''))

print('\n' + '-' * 80 + '\n')




In [ ]:
def rotate_vector(vec: np.typing.ArrayLike = np.array([0, 0]), degrees: int = 90, axis: str = 'x') -> None:
    if vec.shape[0] > 3:
        raise ValueError("Vector must have 2 or 3 dimensions.")

    theta = np.radians(degrees)
    R = np.eye(vec.shape[0])  # Instantiated and but not used
    rotated_vec = np.zeros_like(vec)  # Instantiated and but not used

    if vec.shape[0] == 3:

        if axis == 'z':
            R = np.array([[np.cos(theta), -np.sin(theta), 0], [np.sin(theta), np.cos(theta), 0], [0, 0, 1]])
        elif axis == 'y':
            R = np.array([[np.cos(theta), 0, np.sin(theta)], [0, 1, 0], [-np.sin(theta), 0, np.cos(theta)]])
        elif axis == 'x':
            R = np.array([[1, 0, 0], [0, np.cos(theta), -np.sin(theta)], [0, np.sin(theta), np.cos(theta)]])
        else:
            raise ValueError("Invalid axis. Must be 'x', 'y', or 'z'.")

        rotated_vec = np.dot(R, vec)

        print('\n' + '-' * 80 + '\n')

        print("Rotated vector:\n")

        print(f"x = {round(rotated_vec[0], 2)}")
        print(f"y = {round(rotated_vec[1], 2)}")
        print(f"z = {round(rotated_vec[2], 2)}")

        print('\n' + '-' * 80 + '\n')



    elif vec.shape[0] == 2:

        # Define the rotation matrix rotation for 2d
        R = np.array([[np.cos(theta), -np.sin(theta)],
                      [np.sin(theta), np.cos(theta)]])

        # Apply the rotation to the vector 
        rotated_vec = np.dot(R, vec)
        print('\n' + '-' * 80 + '\n')

        print("Rotated vector:\n")

        print(f"x = {round(rotated_vec[0], 2)}")
        print(f"y = {round(rotated_vec[1], 2)}")

        print('\n' + '-' * 80 + '\n')



In [ ]:
rotate_vector(np.array([-2, 3, -1]), 225, 'x')

# Adding and Scaling Linear Transformations
***

In [ ]:
print('\n' + '-' * 80 + '\n')
display(Math(
    r'S: \space \mathbb{R}^n \rightarrow \mathbb{R}^m \space\space\space A\overrightarrow{X} \space\space\space A = M \space x \space N'))
display(Math(
    r'T: \space \mathbb{R}^n \rightarrow \mathbb{R}^m \space\space\space B\overrightarrow{X} \space\space\space B = M \space x \space N'))
print('\n' + '-' * 80 + '\n')


In [ ]:
print('\n' + '-' * 80 + '\n')
display(Math('(S + T)(\overrightarrow{X}) = S(\overrightarrow{X}) + T(\overrightarrow{X})'))
display(Math(r'\hspace{53pt} = A\overrightarrow{X} + B\overrightarrow{X}'))
display(Math(r'\hspace{53pt} = (A + B)\overrightarrow{X}'))
print('\n' + '-' * 80 + '\n')

In [ ]:
# Question 1: Find the product of a scalar c = −3 and the transformation T(⃗ x ).

T_x = np.array([[2, -1], [0, 5]])

c = -3

T_c_x = c * T_x

In [ ]:
T_c_x

In [ ]:
# Question 2: Find the sum of the transformations S(⃗ x ) and T(⃗ x ).


S_x = np.array([[3, 6], [0, -1]])

T_x = np.array([[-1, 4], [2, 4]])

S_plus_T_x = S_x + T_x

S_plus_T_x

# Projections as Linear Transformations
***

In [ ]:

print('\n' + '-' * 80 + '\n')
display(Math(
    r'P_L(\overrightarrow{v}) \space = \space (\frac{\overrightarrow{v} \cdot \overrightarrow{x}}{\overrightarrow{x} \cdot \overrightarrow{x}}) \space \overrightarrow{x}'))
print('\n' + '-' * 80 + '\n')
display(Math(
    r'c \space = \space \frac{\overrightarrow{v} \space \cdot \space \overrightarrow{v}}{\overrightarrow{x} \space \cdot \space \overrightarrow{x}} \space'))
print('\n' + '-' * 80 + '\n')
display(Math(r'c \space = \space \frac{\overrightarrow{v} \cdot \overrightarrow{x}}{||\overrightarrow{x}||^2} \space'))
print('\n' + '-' * 80 + '\n')
display(Math(r'c \space = \space \overrightarrow{v} \cdot \overrightarrow{x}'))
print('\n' + '-' * 80 + '\n')
display(Math(
    r'(\overrightarrow{v} \cdot \overrightarrow{x}) \space) \space \overrightarrow{x} = \space (\overrightarrow{v} \cdot \hat{u}) \space \hat{u}'))
print('\n' + '-' * 80 + '\n')

In [ ]:
display(Math(
    r'c \space = \space \frac{\overrightarrow{v} \space \cdot \space \overrightarrow{v}}{\overrightarrow{x} \space \cdot \space \overrightarrow{x}} \space'))

In [ ]:
# Question 1: Given the vector v = (-2, 0), find the projection of v onto L

x = np.array([-2, 0])
v = np.array([1, 5])

c = (np.dot(v, x) / np.linalg.norm(x) ** 2) * x

c

In [ ]:
# Question 2

x = np.array([3, -4])
v = np.array([-2, -1])

c = (np.dot(v, x) / np.linalg.norm(x) ** 2) * x

c

# Composition of Linear Transformations
***
In order to compose linear transformations, we multiply the matrices representing the transformations in the reverse order.

First multiplying the transformation matrices S and T, then multiplying the result by the transformation matrix R.

In [ ]:
def compose_transformations(S: np.ndarray, T: np.ndarray, x: np.ndarray) -> np.ndarray:
    R_x = T @ S

    return R_x.dot(x)

In [ ]:
# Question 1: If S : X → Y and T : Y → Z, then what is T(S(⃗ x ))?

z = compose_transformations(
    S=np.array([[-1, 1], [3, 0]]),
    T=np.array([[2, -1], [0, -2]]),
    x=np.array([1, -1]))

z

In [ ]:
z = compose_transformations(
    S=np.array([[2, 0], [-1, 4]]),
    T=np.array([[-1, -2], [3, 0]]),
    x=np.array([3, 2])
)

z

In [ ]:
z = compose_transformations(
    S=np.array([[1, -1, 2], [-4, 0, 0], [0, 1, -1]]),
    T=np.array([[0, 0, -3], [1, -2, 0], [4, 0, 0]]),
    x=np.array([[2], [-4], [0]])
)

z